### ISSUE TITLE
Thank You for Creating This

### ISSUE THREAD

**Issue by Lonniebiz** [jancc/vma-extractor#1]
Sorry to abuse the issue system, but I saw no other way to express my gratitude for you creating this vma-extractor. I wish Promox offered the option to backup to a true raw file, and not this VMA obfuscation. I don't understand the reason for VMA even existing unless it is to deter migration to non-proxmox alternatives. This is not the type of behavior I'd expect from an open source project. Perhaps I'm completely wrong, and there are other legitimate reasons for VMA's existence, but no one yet has offered a reason I'd consider legitimate. Feel free too disabuse my speculation.

I posted my concern here:
https://forum.proxmox.com/threads/vma-archive-restore-outside-of-proxmox.14226/post-474023

**Comment by jancc** [comment]
Thank you so much, that actually means a lot to me <3
